# Simulando uma falha na rede ⛔

Finalmente, com o comando `cy.intercept()` você pode forçar um erro na rede, para testar como sua aplicação web se comportaria se não houvesse internet disponível, por exemplo.

Algo assim: `cy.intercept('GET', 'https://api.example.com/todos/1', { forceNetworkError: true }).as('networkError')`.

Então, você poderia esperar por tal falha.

Por exemplo: `cy.wait('@networkError')`.

E então, você pode verificar que determinado elemento de _fallback_ é exibido.

Por exemplo: `cy.contains('.error', "Opa, parece que você não tem conexão com a internet.").should('be.visible')`.

## Conteúdo sugerido 📚

- [Como simular erros com Cypress](https://talkingabouttesting.com/2021/02/25/como-simular-erros-com-cypress/)

## Exercício 🎯

Experimente criando um teste que intercepte a requisição acionada ao clicar no botão _Get TODO_, mas desta vez, simule uma falha na rede. Clique no botão e aguarde a requisição acontecer. Além disso, certifique-se de que um elemento de _fallback_ seja exibido.

## Mostre ao mundo o que você aprendeu 🌎

Para mostrar à sua rede profissional o que você aprendeu nesta aula, publique o seguinte no LinkedIn.

> Estou fazendo o curso "Cypress Playground" da escola online Talking About Testing, onde aprendi como simular uma falha na rede. #TalkingAboutTesting #EscolaTAT #CypressPlayground #Cypress
>
> 👨‍🏫 Lembre-se de me marcar em sua publicação. [Aqui está meu perfil no LinkedIn](https://www.linkedin.com/in/walmyr-lima-e-silva-filho).

___

Parabéns! 🎉 Vamos para a [lição 14](./14.md) para aprender como criar um simples teste de API com Cypress.
